using UnityEngine;
public class Events
{
    // Fields
    public static string PLAY_PORTRAIT;
    public static string PLAY_LANDSCAPE;
    public static string APP_OPENED;
    public static string LOGIN;
    public static string SIGN_UP_FTUX;
    public static string BUCKET;
    public static string PROCESSOR_TYPE;
    public static string PROCESSOR_COUNT;
    public static string SYSTEM_MEMORY_SIZE;
    public static string GRAPHICS_MEMORY_SIZE;
    public static string GRAPHICS_DEVICE_NAME;
    public static string GRAPHICS_DEVICE_VENDOR;
    public static string GAME_INITIATED_FTUX;
    public const string VIP_POINTS_COLLECTED = "Vip Points Collected";
    public const string DEEPLINK_PARSED = "Deeplink Parsed";
    public const string LUCKY_DAY = "Lucky Day";
    public const string REVIEW_PROMPT = "Review Prompt";
    public static string TRANSACTION;
    public static string TRANSACTION_FAILED;
    public static string NAME;
    public static string PURCHASE_CREDITS;
    public static string PERIODIC_CREDITS;
    public static string LEVEL_UP;
    public static string CURRENT_LEVEL;
    public static string OUT_OF_CREDITS;
    public static string PURCHASE_INTENT;
    public static string MOST_RECENT_PURCHASE;
    public static string LIFETIME_REVENUE;
    public static string APPLICATION_VERSION;
    public static string FOOD_SPENT;
    public static string CARDS_SPENT;
    public static string APP_LAUNCHED;
    public static string DAILY_BONUS;
    public static string HINT_USED;
    public static string HINT_USED_16;
    public static string HINT_USED_20;
    public static string HINT_USED_25;
    public static string HINT_USED_30;
    public static string HINT_USED_35;
    public static string HINT_USED_40;
    public static string HINT_USED_50;
    public static string DAILY_CHALLENGE_BUY_GUESS;
    public static string STRUGGLE_HINT_USED;
    public static string SOUND_ON;
    public static string SOUND_OFF;
    public static string REVENUE_IAP;
    public static string FIRST_PURCHASE;
    public static string REPEAT_PURCHASER;
    public static string PURCHASE_099;
    public static string PURCHASE_199;
    public static string PURCHASE_299;
    public static string PURCHASE_399;
    public static string PURCHASE_499;
    public static string PURCHASE_599;
    public static string PURCHASE_799;
    public static string PURCHASE_999;
    public static string PURCHASE_1199;
    public static string PURCHASE_1499;
    public static string PURCHASE_1699;
    public static string PURCHASE_1999;
    public static string PURCHASE_4999;
    public static string PURCHASE_9999;
    public static string PURCHASE_19999;
    public static string TOTAL_PURCHASE_THRESHOLD_50;
    public static string TOTAL_PURCHASE_THRESHOLD_100;
    public static string TOTAL_PURCHASE_THRESHOLD_500;
    public static string TOTAL_PURCHASE_THRESHOLD_1000;
    public static string SUBSCRIPTION_PURCHASE;
    public static string SUBSCRIPTION_TRIAL_START;
    public static string STARTERPACK_PURCHASE;
    public static string BUNDLE_PURCHASE;
    public static string PURCHASE_GEMS;
    public static string PURCHASE_FOOD;
    public static string PURCHASE_2499;
    public static string PURCHASE_HOURS_01;
    public static string PURCHASE_HOURS_12;
    public static string PURCHASE_HOURS_24;
    public static string PURCHASE_HOURS_168;
    public static string AD_SEEN_NON_REWARDED;
    public static string FB_LOGIN;
    public static string AD_SEEN_ALL;
    public static string AD_SEEN_REW_VID;
    public static string AD_SEEN_REW_VID_OOC;
    public static string AD_SEEN_REW_VID_FTUX;
    public static string AD_SEEN_REW_VID_DB;
    public static string AD_SEEN_REW_VID_PA_DB;
    public static string AD_SEEN_REW_VID_BUTTON;
    public static string AD_SEEN_REW_VID_PL;
    public static string AD_SEEN_REW_LEAGUES_CONTRIBUTE;
    public static string AD_SEEN_REW_LEAGUES_CREATE;
    public static string AD_SEEN_REW_VID_MG_OOC;
    public static string AD_SEEN_REW_VID_WATERFALL;
    public static string AD_REVENUE;
    public static string AD_SEEN_REW_VID_OOS;
    public static string AD_SEEN_REW_VID_OOS_BUTTON;
    public static string AD_SEEN_INT;
    public static string AD_SEEN_BANNER;
    public static string REW_VID_05;
    public static string REW_VID_10;
    public static string REW_VID_15;
    public static string REW_VID_20;
    public static string REW_VID_25;
    public static string REW_VID_50;
    public static string REW_VID_100;
    public static string REW_VID_250;
    public static string REW_VID_500;
    public static string AD_CLICK_05;
    public static string AD_CLICK_10;
    public static string AD_CLICK_15;
    public static string AD_CLICK_20;
    public static string AD_CLICK_30;
    public static string AD_CLICK_50;
    public static string AD_CLICK_100;
    public static string ADS_DISABLED_REW;
    public static string PIGGY_NONBUYER;
    public static string PIGGY_LAPSE1;
    public static string PIGGY_LAPSE2;
    public static string PIGGY_LAPSE3;
    public static string OFFER_WALL_COMPLETE;
    public static string OFFER_WALL_05;
    public static string OFFER_WALL_10;
    public static string OFFER_WALL_15;
    public static string OFFER_WALL_20;
    public static string OFFER_WALL_25;
    public static string OFFER_WALL_50;
    public static string SURVEY_COMPLETE;
    public static string SURVEY_05;
    public static string SURVEY_10;
    public static string SURVEY_15;
    public static string SURVEY_20;
    public static string SURVEY_25;
    public static string SURVEY_50;
    public static string RETENTION_D1;
    public static string RETENTION_D2;
    public static string RETENTION_D3;
    public static string RETENTION_D6;
    public static string RETENTION_D7;
    public static string RETENTION_D30;
    public static string RETENTION_D2_CONSECUTIVE;
    public static string RETENTION_D3_CONSECUTIVE;
    public static string RETENTION_D6_CONSECUTIVE;
    public static string RETENTION_D7_CONSECUTIVE;
    public static string RETENTION_D30_CONSECUTIVE;
    public static string D1_SUB_PURCHASE;
    public static string D3_SUB_PURCHASE;
    public static string D1_AD_CLICKED_10;
    public static string D1_REW_VID_05;
    public static string D3_AD_CLICKED_10;
    public static string D3_REW_VID_05;
    public static string PUR_RET_0101;
    public static string PUR_RET_0103;
    public static string PUR_RET_0107;
    public static string PUR_RET_0501;
    public static string PUR_RET_0503;
    public static string PUR_RET_0507;
    public static string PUR_RET_1001;
    public static string PUR_RET_1003;
    public static string PUR_RET_1007;
    public static string LEVEL_REACHED;
    public static string D1_LEVEL_100;
    public static string D3_LEVEL_100;
    public static string IQ_MILESTONE;
    public static string IQ_MILESTONE_1;
    public static string IQ_MILESTONE_2;
    public static string IQ_MILESTONE_3;
    public static string IQ_MILESTONE_4;
    public static string STORE_PACK_SELECTED;
    public static string STORE_PURCHASE_SUCCESS;
    public static string STORE_PURCHASE_FAILED;
    public static string NOTIFICATAION_ALL;
    public static string NOTIFICATAION_BONUS_CREDITS;
    public static string NOTIFICATAION_HAPPY_HOUR;
    public static string NOTIFICATAION_DAILY_REMINDER;
    public static string NOTIFICATAION_REBUYBONUS_REMINDER;
    public static string GAMEPLAY_QUIT;
    public static string GAMEPLAY_QUIT_BUTTON_YES;
    public static string GAMEPLAY_QUIT_BUTTON_NO;
    public static string GAMEPLAY_EXIT_APP;
    public static string GAMEPLAY_GET_KEY;
    public static string BUY_BUTTON;
    public const string SESSION_START = "Start Session";
    public const string SESSION_ENDS = "End Session";
    public const string NOTIFICATION_OPEN = "Notification Opened ";
    public const string DO_NOT_TRACK = "Not Tracked";
    public const string PURCHASES_HANDLER = "PurchasesHandler";
    public const string MOREGAMES = "MoreGamesBonus";
    public const string AWARD = "Award";
    public const string LOW_MEMORY = "LowMemory";
    public const string WG_FREE_COINS = "Free Coins";
    public const string WG_NON_COIN_AWARD = "NonCoin Award";
    public const string WG_DAILY_BONUS_HINT_DISCOUNT = "Daily Bonus Hint Discount";
    public const string WG_ADS_CONTROL_TIME_FROM_ADS = "Ads Control Time From Ads";
    public const string WG_DAILY_BONUS = "Daily Bonus Reward {0}";
    public const string WG_CHAPTER_CLEAR = "Chapter Complete";
    public const string WG_CHAPTER_CLEAR_HINT_DISCOUNT = "Chapter Complete Hint Discount";
    public const string WG_EXTRA_WORDS = "Extra Words";
    public const string WG_WORD_COIN = "Word Coin Bonus";
    public const string WG_RATE_BONUS = "Rate Bonus";
    public const string WG_FRIEND_INVITER = "Friend Inviter";
    public const string WG_FB_CONNECT = "FB Connect Bonus";
    public const string WG_DAILY_CHALLENGE = "Daily Challenge Stage {0}";
    public const string WG_CREDITS_SPENT = "Coins Spent";
    public const string WG_HINT = "Hint";
    public const string WG_PICKER_HINT = "Picker Hint";
    public const string WG_MEGA_HINT = "Mega Hint";
    public const string WG_AD_DISPLAY = "Ad Display";
    public const string WG_AD_CLICK = "Ad Clicked";
    public const string WG_LEVEL_START = "Level Start";
    public const string WG_LEVEL_COMPLETE = "Level Complete";
    public const string WG_LEVEL_END = "Level End";
    public const string WG_DAILY_CHALLENGE_STAGE_COMPLETE = "Daily Challenges";
    public const string WG_WILD_WEEKEND_COMPLETE = "Wild Weekend Complete";
    public const string WG_EMAIL_COLLECTION_PROMPT = "Email Collection";
    public const string WG_DAILY_BONUS_FB = "Daily Bonus FB Friends";
    public const string WG_GOTD_Shown = "GOTD Shown";
    public const string WG_GOTD_Clicked = "GOTD Clicked";
    public const string WG_SPEED_CHALLENGE_REW_SOURCE = "Speed Challenge Reward";
    public const string WG_SPEED_CHALLENGE_TIME_REW_SOURCE = "Speed Challenge Time From Ad";
    public const string WG_SPEED_CHALLENGE_STAGE_END = "Speed Challenge End";
    public const string WG_SPEED_CHALLENGE_START = "Speed Challenge Start";
    public const string WG_INTERSTITIAL_SHOWN = "Interstitial Shown";
    public const string WG_PARTNER_REWARD_SOURCE = "Daily Challenge Partner Reward";
    public const string WG_DC_GUESS_AGAIN = "Daily Challenge Guess Again";
    public const string WG_MINIGAME_CONTINUE = "MG Continue From Ads";
    public const string WG_MINIGAME_LIVES = "MG Lives From Ads";
    public const string WG_ALPHABET_COLLECTION = "Alphabet Collection";
    public const string WG_ALPHABET_TILE_VID_REW = "Video_Ad_Alphabet_Tile";
    public const string WG_BONUSGAME_WHEEL = "Bonus Game Wheel";
    public const string WG_BONUSGAME_SLOTMACHINE = "Bonus Game Slot Machine";
    public const string LEAGUES_FIRST_JOIN_REWARD = "Leagues Join Reward";
    public const string LEAGUES_GUILD_JOIN = "Leagues Join Club";
    public const string LEAGUES_GUILD_LEAVE = "Leagues Leave Club";
    public const string LEAGUES_DAILY_ROLLOVER = "Leagues Daily Rollover";
    public const string LEAGUES_SEASON_ROLLOVER = "Leagues Season Rollover";
    public const string LEAGUES_SEASON_REWARD = "Leagues Season Reward";
    public const string LEAGUES_CONTRIBUTION = "Leagues Contribution";
    public const string LEAGUES_DAILY_REWARD = "Daily First Golden Currency Reward";
    public const string CLUB_WALL_POSTS_MADE_TOTAL = "Total Club Wall Posts Made";
    public const string WG_CHECK = "Check";
    public const string WG_SUD_LEVEL_UP = "Level Up {0}";
    public const string WG_LEVEL_CHALLENGE = "Level_Challenge";
    public const string WG_LEVEL_CHALLENGE_ALT = "Level Challenge";
    public const string WG_ALPHABET_HINT_DISCOUNT = "Alphabet Hint Discount Reward";
    public const string WG_MYSTERY_GIFT_REWARD = "Mystery Gift";
    public const string WG_MINIGAME_SESSION = "Mini Game Session";
    public const string WG_TIMELINE = "Timeline";
    public const string GOLDEN_CURRENCY_SPENT = "Golden Currency Spent";
    public const string WG_GEMS_SPENT = "Gems Spent";
    public const string AUTO_BREADCRUMB = "auto_breadcrumb";
    public const string AUTO_ERROR = "auto_errors";
    public const string AUTO_STOP_ACTIONS = "auto_stop_actions";
    public const string BBL_ZEN_MODE_START = "Zen Mode Start";
    public const string BBL_ZEN_MODE_COMPLETE = "Zen Mode Complete";
    public const string TRV_Level_Start = "TRV Level Start";
    public const string TRV_Level_Complete = "TRV Level Complete";
    public const string Challenge_Friend_Issued = "Challenge Friend";
    public const string Challenge_Friend_Ended = "Challenge Friend End";
    public const string WFO_INITIAL_FOREST_ENTRY = "Initial Forest Entry";
    public const string RAID_COMPLETE = "Raid Complete";
    public const string RAIDED = "Raided";
    public const string ATTACK_COMPLETE = "Attack Complete";
    public const string ATTACKED = "Attacked";
    public const string SLOT_SESSION_COMPLETE = "Slot Game Session Complete";
    public const string TOURNAMENT_ROLLOVER = "Tournament Rollover";
    
    // Methods
    public Events()
    {
    
    }
    private static Events()
    {
        Events.TOURNAMENT_ROLLOVER = "Play Portrait";
        Events.PLAY_LANDSCAPE = "Play Landscape";
        Events.APP_OPENED = "App Opened";
        Events.LOGIN = "Login";
        Events.SIGN_UP_FTUX = "Sign Up";
        Events.BUCKET = "Bucket";
        Events.PROCESSOR_TYPE = "Processor Type";
        Events.PROCESSOR_COUNT = "Processor Count";
        Events.SYSTEM_MEMORY_SIZE = "System Memory Size";
        Events.GRAPHICS_MEMORY_SIZE = "Graphics Memory Size";
        Events.GRAPHICS_DEVICE_NAME = "Graphics Device Name";
        Events.GRAPHICS_DEVICE_VENDOR = "Graphics Device Vendor";
        Events.GAME_INITIATED_FTUX = "Game Initiated";
        Events.TRANSACTION = "Transaction";
        Events.TRANSACTION_FAILED = "Transaction Failed";
        Events.NAME = "Name";
        Events.PURCHASE_CREDITS = "Purchase Credits";
        Events.PERIODIC_CREDITS = "Periodic Credits";
        Events.LEVEL_UP = "Level Up";
        Events.CURRENT_LEVEL = "Current Level";
        Events.OUT_OF_CREDITS = "Out of Credits";
        Events.PURCHASE_INTENT = "Purchase Intent";
        Events.MOST_RECENT_PURCHASE = "Most Recent Purchase";
        Events.LIFETIME_REVENUE = "Lifetime Revenue";
        Events.APPLICATION_VERSION = "Application Version";
        Events.FOOD_SPENT = "Food Spent";
        Events.CARDS_SPENT = "Cards Spent";
        Events.APP_LAUNCHED = "app_launched";
        Events.DAILY_BONUS = "daily_bonus";
        Events.HINT_USED = "hint_used";
        Events.HINT_USED_16 = "hint_used_16";
        Events.HINT_USED_20 = "hint_used_20";
        Events.HINT_USED_25 = "hint_used_25";
        Events.HINT_USED_30 = "hint_used_30";
        Events.HINT_USED_35 = "hint_used_35";
        Events.HINT_USED_40 = "hint_used_40";
        Events.HINT_USED_50 = "hint_used_50";
        Events.DAILY_CHALLENGE_BUY_GUESS = "dc_buy_guess";
        Events.STRUGGLE_HINT_USED = "struggle_hint_used";
        Events.SOUND_ON = "sound_on";
        Events.SOUND_OFF = "sound_off";
        Events.REVENUE_IAP = "revenue_iap";
        Events.FIRST_PURCHASE = "first_purchase";
        Events.REPEAT_PURCHASER = "repeat_purchaser";
        Events.PURCHASE_099 = "purchase_099";
        Events.PURCHASE_199 = "purchase_199";
        Events.PURCHASE_299 = "purchase_299";
        Events.PURCHASE_399 = "purchase_399";
        Events.PURCHASE_499 = "purchase_499";
        Events.PURCHASE_599 = "purchase_599";
        Events.PURCHASE_799 = "purchase_799";
        Events.PURCHASE_999 = "purchase_999";
        Events.PURCHASE_1199 = "purchase_1199";
        Events.PURCHASE_1499 = "purchase_1499";
        Events.PURCHASE_1699 = "purchase_1699";
        Events.PURCHASE_1999 = "purchase_1999";
        Events.PURCHASE_4999 = "purchase_4999";
        Events.PURCHASE_9999 = "purchase_9999";
        Events.PURCHASE_19999 = "purchase_19999";
        Events.TOTAL_PURCHASE_THRESHOLD_50 = "total_purchase_threshold_50";
        Events.TOTAL_PURCHASE_THRESHOLD_100 = "total_purchase_threshold_100";
        Events.TOTAL_PURCHASE_THRESHOLD_500 = "total_purchase_threshold_500";
        Events.TOTAL_PURCHASE_THRESHOLD_1000 = "total_purchase_threshold_1000";
        Events.SUBSCRIPTION_PURCHASE = "subscription_purchase";
        Events.SUBSCRIPTION_TRIAL_START = "subscription_trial_start";
        Events.STARTERPACK_PURCHASE = "purchase_499_starter_pack";
        Events.BUNDLE_PURCHASE = "purchase_bundle";
        Events.PURCHASE_GEMS = "purchase_gems";
        Events.PURCHASE_FOOD = "purchase_food";
        Events.PURCHASE_2499 = "purchase_2499";
        Events.PURCHASE_HOURS_01 = "purchase_hours_01";
        Events.PURCHASE_HOURS_12 = "purchase_hours_12";
        Events.PURCHASE_HOURS_24 = "purchase_hours_24";
        Events.PURCHASE_HOURS_168 = "purchase_hours_168";
        Events.AD_SEEN_NON_REWARDED = "ad_seen_non_rewarded";
        Events.FB_LOGIN = "fb_login";
        Events.AD_SEEN_ALL = "ad_seen_all";
        Events.AD_SEEN_REW_VID = "ad_seen_rewarded_video";
        Events.AD_SEEN_REW_VID_OOC = "ad_seen_rewarded_video_ooc";
        Events.AD_SEEN_REW_VID_FTUX = "ad_seen_rewarded_video_auto";
        Events.AD_SEEN_REW_VID_DB = "ad_seen_rewarded_video_db";
        Events.AD_SEEN_REW_VID_PA_DB = "ad_seen_rewarded_pick_another_db";
        Events.AD_SEEN_REW_VID_BUTTON = "ad_seen_rewarded_video_button";
        Events.AD_SEEN_REW_VID_PL = "ad_seen_rewarded_level_complete";
        Events.AD_SEEN_REW_LEAGUES_CONTRIBUTE = "ad_seen_rewarded_club_contribute";
        Events.AD_SEEN_REW_LEAGUES_CREATE = "ad_seen_rewarded_club_create";
        Events.AD_SEEN_REW_VID_MG_OOC = "ad_seen_rewarded_video_mg_ooc";
        Events.AD_SEEN_REW_VID_WATERFALL = "ad_seen_rewarded_video_waterfall";
        Events.AD_REVENUE = "Ad Revenue";
        Events.AD_SEEN_REW_VID_OOS = "ad_seen_rewarded_video_oos";
        Events.AD_SEEN_REW_VID_OOS_BUTTON = "ad_seen_rewarded_video_oos_button";
        Events.AD_SEEN_INT = "ad_seen_interstitial";
        Events.AD_SEEN_BANNER = "ad_seen_banner";
        Events.REW_VID_05 = "rewarded_video_05";
        Events.REW_VID_10 = "rewarded_video_10";
        Events.REW_VID_15 = "rewarded_video_15";
        Events.REW_VID_20 = "rewarded_video_20";
        Events.REW_VID_25 = "rewarded_video_25";
        Events.REW_VID_50 = "rewarded_video_50";
        Events.REW_VID_100 = "rewarded_video_100";
        Events.REW_VID_250 = "rewarded_video_250";
        Events.REW_VID_500 = "rewarded_video_500";
        Events.AD_CLICK_05 = "ad_clicked_05";
        Events.AD_CLICK_10 = "ad_clicked_10";
        Events.AD_CLICK_15 = "ad_clicked_15";
        Events.AD_CLICK_20 = "ad_clicked_20";
        Events.AD_CLICK_30 = "ad_clicked_30";
        Events.AD_CLICK_50 = "ad_clicked_50";
        Events.AD_CLICK_100 = "ad_clicked_100";
        Events.ADS_DISABLED_REW = "ad_disabled_rewarded";
        Events.PIGGY_NONBUYER = "purchase_piggy_nonbuyer";
        Events.PIGGY_LAPSE1 = "purchase_piggy_lapse1";
        Events.PIGGY_LAPSE2 = "purchase_piggy_lapse2";
        Events.PIGGY_LAPSE3 = "purchase_piggy_lapse3";
        Events.OFFER_WALL_COMPLETE = "offer_wall_complete";
        Events.OFFER_WALL_05 = "offer_wall_05";
        Events.OFFER_WALL_10 = "offer_wall_10";
        Events.OFFER_WALL_15 = "offer_wall_15";
        Events.OFFER_WALL_20 = "offer_wall_20";
        Events.OFFER_WALL_25 = "offer_wall_25";
        Events.OFFER_WALL_50 = "offer_wall_50";
        Events.SURVEY_COMPLETE = "survey_complete";
        Events.SURVEY_05 = "survey_05";
        Events.SURVEY_10 = "survey_10";
        Events.SURVEY_15 = "survey_15";
        Events.SURVEY_20 = "survey_20";
        Events.SURVEY_25 = "survey_25";
        Events.SURVEY_50 = "survey_50";
        Events.RETENTION_D1 = "retention_d1";
        Events.RETENTION_D2 = "retention_d2";
        Events.RETENTION_D3 = "retention_d3";
        Events.RETENTION_D6 = "retention_d6";
        Events.RETENTION_D7 = "retention_d7";
        Events.RETENTION_D30 = "retention_d30";
        Events.RETENTION_D2_CONSECUTIVE = "retention_d2_consecutive";
        Events.RETENTION_D3_CONSECUTIVE = "retention_d3_consecutive";
        Events.RETENTION_D6_CONSECUTIVE = "retention_d6_consecutive";
        Events.RETENTION_D7_CONSECUTIVE = "retention_d7_consecutive";
        Events.RETENTION_D30_CONSECUTIVE = "retention_d30_consecutive";
        Events.D1_SUB_PURCHASE = "d1_subscription_purchase";
        Events.D3_SUB_PURCHASE = "d3_subscription_purchase";
        Events.D1_AD_CLICKED_10 = "d1_ad_clicked_10";
        Events.D1_REW_VID_05 = "d1_rewarded_video_05";
        Events.D3_AD_CLICKED_10 = "d3_ad_clicked_10";
        Events.D3_REW_VID_05 = "d3_rewarded_video_05";
        Events.PUR_RET_0101 = "purchase_retention_0101";
        Events.PUR_RET_0103 = "purchase_retention_0103";
        Events.PUR_RET_0107 = "purchase_retention_0107";
        Events.PUR_RET_0501 = "purchase_retention_0501";
        Events.PUR_RET_0503 = "purchase_retention_0503";
        Events.PUR_RET_0507 = "purchase_retention_0507";
        Events.PUR_RET_1001 = "purchase_retention_1001";
        Events.PUR_RET_1003 = "purchase_retention_1003";
        Events.PUR_RET_1007 = "purchase_retention_1007";
        Events.LEVEL_REACHED = "level";
        Events.D1_LEVEL_100 = "d1_lvl_100";
        Events.D3_LEVEL_100 = "d3_lvl_100";
        Events.IQ_MILESTONE = "iq_milestone";
        Events.IQ_MILESTONE_1 = "iq_milestone_1";
        Events.IQ_MILESTONE_2 = "iq_milestone_2";
        Events.IQ_MILESTONE_3 = "iq_milestone_3";
        Events.IQ_MILESTONE_4 = "iq_milestone_4";
        Events.STORE_PACK_SELECTED = "Pack clicked";
        Events.STORE_PURCHASE_SUCCESS = "Purchase successful";
        Events.STORE_PURCHASE_FAILED = "Purchase failed";
        Events.NOTIFICATAION_ALL = "All notification changed";
        Events.NOTIFICATAION_BONUS_CREDITS = "Bonus credits notification changed";
        Events.NOTIFICATAION_HAPPY_HOUR = "Happy hour notification changed";
        Events.NOTIFICATAION_DAILY_REMINDER = "Daily reminder notification changed";
        Events.NOTIFICATAION_REBUYBONUS_REMINDER = "Rebuy bonus reminder notification changed";
        Events.GAMEPLAY_QUIT = "Quit pop up open";
        Events.GAMEPLAY_QUIT_BUTTON_YES = "Yes quit button";
        Events.GAMEPLAY_QUIT_BUTTON_NO = "No quit button";
        Events.GAMEPLAY_EXIT_APP = "App closed";
        Events.GAMEPLAY_GET_KEY = "Received Free Key";
        Events.BUY_BUTTON = "Buy Button";
    }

}
