using UnityEngine;
public class ZooTilePool
{
    // Fields
    public static System.Collections.Generic.List<ZooTile> LifetimeZooTiles;
    public static System.Collections.Generic.List<ZooTile> MonthlyZooTiles;
    
    // Methods
    public ZooTilePool()
    {
    
    }
    private static ZooTilePool()
    {
        System.Collections.Generic.List<twelvegigs.sweepstakes.Distribution> val_1 = new System.Collections.Generic.List<twelvegigs.sweepstakes.Distribution>();
        object val_2 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Sheep";
        typeof(ZooTile).__il2cppRuntimeField_C = 1;
        typeof(ZooTile).__il2cppRuntimeField_10 = "A sheep\'s wool never stops growing.";
        Add(item:  387379200);
        object val_3 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Sloth";
        typeof(ZooTile).__il2cppRuntimeField_C = 5;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Sloths can take a week to digest their food.";
        Add(item:  387379200);
        object val_4 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Chinchilla";
        typeof(ZooTile).__il2cppRuntimeField_C = 10;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Chinchillas bathe in volcanic ash to keep their fur clean.";
        Add(item:  387379200);
        object val_5 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Penguin";
        typeof(ZooTile).__il2cppRuntimeField_C = 15;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Penguins give their mates a rock or pebble as a gift.";
        Add(item:  387379200);
        object val_6 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Wolf";
        typeof(ZooTile).__il2cppRuntimeField_C = 25;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Wolves live in packs of up to 20.";
        Add(item:  387379200);
        object val_7 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Ostrich";
        typeof(ZooTile).__il2cppRuntimeField_C = 50;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Ostriches can run faster than most horses.";
        Add(item:  387379200);
        object val_8 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Crocodile";
        typeof(ZooTile).__il2cppRuntimeField_C = 75;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Crocodiles do not have sweat glands and release heat through their mouths. They often sleep with their mouths open and may pant like a dog.";
        Add(item:  387379200);
        object val_9 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Zebra";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Every zebra has a unique pattern of black and white stripes.";
        Add(item:  387379200);
        object val_10 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Kangaroo";
        typeof(ZooTile).__il2cppRuntimeField_C = 125;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Kangaroos cannot walk backwards.";
        Add(item:  387379200);
        object val_11 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Gorilla";
        typeof(ZooTile).__il2cppRuntimeField_C = 150;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Gorillas have unique noseprints, much like human fingerprints, which can be used to identify individuals.";
        Add(item:  387379200);
        object val_12 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Giraffe";
        typeof(ZooTile).__il2cppRuntimeField_C = 175;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Baby giraffes can stand up and even run within an hour of being born.";
        Add(item:  387379200);
        object val_13 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Koala";
        typeof(ZooTile).__il2cppRuntimeField_C = 200;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Koalas can sleep up to 20 hours a day.";
        Add(item:  387379200);
        object val_14 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Owl";
        typeof(ZooTile).__il2cppRuntimeField_C = 250;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Owls can rotate their necks 270 degrees.";
        Add(item:  387379200);
        object val_15 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Hippo";
        typeof(ZooTile).__il2cppRuntimeField_C = 300;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Hippos can\'t swim.";
        Add(item:  387379200);
        object val_16 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Tiger";
        typeof(ZooTile).__il2cppRuntimeField_C = 350;
        typeof(ZooTile).__il2cppRuntimeField_10 = "The tiger is the biggest species of the cat family.";
        Add(item:  387379200);
        object val_17 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Rhino";
        typeof(ZooTile).__il2cppRuntimeField_C = 400;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Rhino horns are made of keratin, the same substance that makes up human nails and hair.";
        Add(item:  387379200);
        object val_18 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Elephant";
        typeof(ZooTile).__il2cppRuntimeField_C = 450;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Elephants can\'t jump.";
        Add(item:  387379200);
        object val_19 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Lion";
        typeof(ZooTile).__il2cppRuntimeField_C = 500;
        typeof(ZooTile).__il2cppRuntimeField_10 = "A lion’s roar can be heard from as far as 5 miles away.";
        Add(item:  387379200);
        object val_20 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Skunk";
        typeof(ZooTile).__il2cppRuntimeField_C = 600;
        typeof(ZooTile).__il2cppRuntimeField_10 = "The smell of a skunk can be detected by a human a mile away.";
        Add(item:  387379200);
        object val_21 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Hummingbird";
        typeof(ZooTile).__il2cppRuntimeField_C = 750;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Hummingbirds beat their wings 60 to 80 times per second.";
        Add(item:  387379200);
        object val_22 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Dolphin";
        typeof(ZooTile).__il2cppRuntimeField_C = 1000;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Dolphins have names for one other.";
        Add(item:  387379200);
        object val_23 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Sea Otter";
        typeof(ZooTile).__il2cppRuntimeField_C = 1500;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Sea otters hold each other\'s paws when they sleep so they don\'t drift apart.";
        Add(item:  387379200);
        object val_24 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Bear";
        typeof(ZooTile).__il2cppRuntimeField_C = 2000;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Bears can be found in almost all areas within the temperate zones of the earth.";
        Add(item:  387379200);
        ZooTilePool.LifetimeZooTiles = null;
        System.Collections.Generic.List<twelvegigs.sweepstakes.Distribution> val_25 = new System.Collections.Generic.List<twelvegigs.sweepstakes.Distribution>();
        object val_26 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Monkey";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Groups of monkeys are known as a ‘tribe’.";
        Add(item:  387379200);
        object val_27 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Rabbit";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Rabbits purr when they’re content.";
        Add(item:  387379200);
        object val_28 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Ant";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "For every human in the world there are one million ants.";
        Add(item:  387379200);
        object val_29 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Snake";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Snakes can open their mouths up to 150 degrees.";
        Add(item:  387379200);
        object val_30 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Beaver";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "The large front teeth of the beaver never stop growing.";
        Add(item:  387379200);
        object val_31 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Snail";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "A snail can sleep for three years.";
        Add(item:  387379200);
        object val_32 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Flamingo";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "A group of flamingos is called a \"flamboyance.\"";
        Add(item:  387379200);
        object val_33 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Woodpecker";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "A woodpecker can peck 20 times per second.";
        Add(item:  387379200);
        object val_34 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Horse";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Horses were domesticated by humans more than 3000 years ago.";
        Add(item:  387379200);
        object val_35 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Lizard";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Lizards can detach their tails if caught by predators.";
        Add(item:  387379200);
        object val_36 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Fox";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Arctic Foxes don\'t shiver until -70° celsius.";
        Add(item:  387379200);
        object val_37 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Moose";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Moose lose their antlers once a year.";
        Add(item:  387379200);
        object val_38 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Pig";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Pigs don\'t sweat.";
        Add(item:  387379200);
        object val_39 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Goat";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Goats were the first animals domesticated by man in 10,000 B.C.";
        Add(item:  387379200);
        object val_40 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Rooster";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Roosters love to crow at any time of day, not just sunrise.";
        Add(item:  387379200);
        object val_41 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Bat";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Bats are the only mammals that can fly.";
        Add(item:  387379200);
        object val_42 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Squirrel";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Millions of trees grow every year thanks to squirrel\'s forgetting where they put their nuts.";
        Add(item:  387379200);
        object val_43 = new System.Object();
        typeof(ZooTile).__il2cppRuntimeField_8 = "Rat";
        typeof(ZooTile).__il2cppRuntimeField_C = 100;
        typeof(ZooTile).__il2cppRuntimeField_10 = "Rats can laugh.";
        Add(item:  387379200);
        ZooTilePool.MonthlyZooTiles = null;
    }

}
